"""Ajout de target_id dans Game

Revision ID: 0b1c078d4f71
Revises: 1f6569a2de2a
Create Date: 2024-12-25 21:47:21.380819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b1c078d4f71'
down_revision = '1f6569a2de2a'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_game_target_id', 'player', ['target_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_constraint('fk_game_target_id', type_='foreignkey')  # Utiliser le nom explicite
        batch_op.drop_column('target_id')

    # ### end Alembic commands ###
