"""Ajout du rôle des joueurs

Revision ID: 1623bde8796e
Revises: 67fabdcb8f14
Create Date: 2024-12-25 18:22:01.612788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1623bde8796e'
down_revision = '67fabdcb8f14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('day_phase_duration', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_column('day_phase_duration')

    # ### end Alembic commands ###
