"""Ajout de target_id dans Game

Revision ID: 1f6569a2de2a
Revises: 9eb10cae7f99
Create Date: 2024-12-25 21:46:51.062083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f6569a2de2a'
down_revision = '9eb10cae7f99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_constraint('fk_game_target_id', type_='foreignkey')
        batch_op.drop_column('target_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_game_target_id', 'player', ['target_id'], ['id'])

    # ### end Alembic commands ###
