"""Ajout de la colonne role dans Player

Revision ID: 22337af66305
Revises: 265d12302fac
Create Date: 2024-12-24 01:57:16.336197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22337af66305'
down_revision = '265d12302fac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column('player', sa.Column('role', sa.String(length=50), nullable=False, server_default='Villageois'))
        batch_op.drop_column('role')
        batch_op.alter_column('player', 'role', server_default=None)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('roleq', sa.VARCHAR(length=50), nullable=False))
        batch_op.drop_column('role')

    # ### end Alembic commands ###
