"""Ajout de la colonne role dans Player

Revision ID: 265d12302fac
Revises: 
Create Date: 2024-12-24 01:57:01.323801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '265d12302fac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column('player', sa.Column('role', sa.String(length=50), nullable=False, server_default='Villageois'))
        batch_op.drop_column('role')
        batch_op.alter_column('player', 'role', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.VARCHAR(length=50), nullable=False))
        batch_op.drop_column('roleq')

    # ### end Alembic commands ###
