"""Initial migration

Revision ID: 2bd36dd3f65c
Revises: 
Create Date: 2025-01-01 20:31:05.045918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bd36dd3f65c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game')
    op.drop_table('user')
    op.drop_table('player')
    op.drop_table('message')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('game_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('game_id', sa.INTEGER(), nullable=False),
    sa.Column('eliminated', sa.BOOLEAN(), nullable=True),
    sa.Column('role', sa.VARCHAR(length=50), nullable=False),
    sa.Column('potion_heal_used', sa.BOOLEAN(), nullable=True),
    sa.Column('potion_poison_used', sa.BOOLEAN(), nullable=True),
    sa.Column('lover_id', sa.INTEGER(), nullable=True),
    sa.Column('seer_used', sa.BOOLEAN(), nullable=True),
    sa.Column('action_used', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.ForeignKeyConstraint(['lover_id'], ['player.id'], name='fk_player_lover_id'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=150), nullable=False),
    sa.Column('email', sa.VARCHAR(length=150), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('game',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('max_players', sa.INTEGER(), nullable=False),
    sa.Column('created_by', sa.INTEGER(), nullable=False),
    sa.Column('started', sa.BOOLEAN(), nullable=True),
    sa.Column('discussion_start_time', sa.DATETIME(), nullable=True),
    sa.Column('current_phase', sa.VARCHAR(length=50), nullable=True),
    sa.Column('phase_start_time', sa.DATETIME(), nullable=True),
    sa.Column('day_phase_duration', sa.INTEGER(), nullable=True),
    sa.Column('night_phase_duration', sa.INTEGER(), nullable=True),
    sa.Column('target_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['player.id'], name='fk_game_target_id'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
