"""Ajout du rôle des joueurs

Revision ID: 67fabdcb8f14
Revises: d58d4b499f40
Create Date: 2024-12-25 17:52:01.247443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67fabdcb8f14'
down_revision = 'd58d4b499f40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seer_used', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_column('seer_used')

    # ### end Alembic commands ###
