"""Ajout des colonnes night_phase_duration et day_phase_duration

Revision ID: 7d6cfa4c1fb7
Revises: d9694c201409
Create Date: 2024-12-25 21:33:16.089457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d6cfa4c1fb7'
down_revision = 'd9694c201409'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('night_phase_duration', sa.Integer(), nullable=True))

    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_column('night_phase_duration')
        batch_op.drop_column('day_phase_duration')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('day_phase_duration', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('night_phase_duration', sa.INTEGER(), nullable=True))

    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_column('night_phase_duration')

    # ### end Alembic commands ###
