"""Ajout de la colonne action_used pour limiter les actions par nuit

Revision ID: 7f4b95255ccc
Revises: 0b1c078d4f71
Create Date: 2025-01-01 02:47:15.590471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f4b95255ccc'
down_revision = '0b1c078d4f71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('action_used', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_column('action_used')

    # ### end Alembic commands ###
