"""Ajout d'une valeur par défaut pour le champ role dans Player

Revision ID: 7f98d5ef3bf5
Revises: 16c3405c5cdf
Create Date: 2025-01-04 20:27:43.307572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f98d5ef3bf5'
down_revision = '16c3405c5cdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('config_roles', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_column('config_roles')

    # ### end Alembic commands ###
