"""Ajout de target_id dans Game

Revision ID: 9eb10cae7f99
Revises: 7d6cfa4c1fb7
Create Date: 2024-12-25 21:43:33.141180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9eb10cae7f99'
down_revision = '7d6cfa4c1fb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'player', ['target_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('target_id')

    # ### end Alembic commands ###
