"""Ajout du rôle des joueurs

Revision ID: d58d4b499f40
Revises: 22337af66305
Create Date: 2024-12-25 17:32:53.665833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd58d4b499f40'
down_revision = '22337af66305'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('potion_heal_used', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('potion_poison_used', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('lover_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_column('lover_id')
        batch_op.drop_column('potion_poison_used')
        batch_op.drop_column('potion_heal_used')

    # ### end Alembic commands ###
