"""Ajout du rôle des joueurs

Revision ID: d9694c201409
Revises: 1623bde8796e
Create Date: 2024-12-25 21:30:48.697626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9694c201409'
down_revision = '1623bde8796e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('night_phase_duration', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('day_phase_duration', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_column('day_phase_duration')
        batch_op.drop_column('night_phase_duration')

    # ### end Alembic commands ###
